[versions]
kotlin = "2.3.10"
ktlint = "14.0.1"
graalvm-native = "0.11.4"
sonarqube = "7.2.2.6593"
jreleaser = "1.22.0"
release = "3.1.0"
clikt = "5.1.0"
konform = "0.11.1"
choco-solver = "5.0.0"
jenetics = "9.0.0"
uuid-generator = "5.1.1"
jgrapht = "1.5.2"
commons-math3 = "3.6.1"
mockk = "1.14.9"
kotest = "6.1.2"
kotlinx-serialization = "1.10.0"
kotlinx-datetime = "0.7.1-0.6.x-compat"
sl4j = "2.0.17"

[libraries]
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
konform-jvm = { module = "io.konform:konform-jvm", version.ref = "konform" }
choco-solver = { module = "org.choco-solver:choco-solver", version.ref = "choco-solver" }
jenetics = { module = "io.jenetics:jenetics", version.ref = "jenetics" }
uuid-generator = { module = "com.fasterxml.uuid:java-uuid-generator", version.ref = "uuid-generator" }
jgrapht-core = { module = "org.jgrapht:jgrapht-core", version.ref = "jgrapht" }
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime-jvm", version.ref = "kotlinx-datetime" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "sl4j" }

# Test libraries
mockk-jvm = { module = "io.mockk:mockk-jvm", version.ref = "mockk" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-konform-jvm = { module = "io.kotest:kotest-assertions-konform-jvm", version.ref = "kotest" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-native" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
release = { id = "net.researchgate.release", version.ref = "release" }

[bundles]
kotest = ["kotest-runner-junit5", "kotest-assertions-core", "kotest-assertions-konform-jvm"]
