[versions]
kotlin = "2.2.21"
kotlinx-kover = "0.9.3"
ktlint = "13.1.0"
graalvm-native = "0.11.2"
sonarqube = "7.0.1.6134"
picocli = "4.7.5"
konform = "0.11.0"
choco-solver = "4.10.18"
uuid-generator = "5.1.1"
jgrapht = "1.5.2"
commons-math3 = "3.6.1"
lets-plot-kotlin = "4.11.2"
lets-plot-image = "4.7.3"
mockk = "1.14.6"
kotest = "6.0.4"

[libraries]
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
konform-jvm = { module = "io.konform:konform-jvm", version.ref = "konform" }
choco-solver = { module = "org.choco-solver:choco-solver", version.ref = "choco-solver" }
uuid-generator = { module = "com.fasterxml.uuid:java-uuid-generator", version.ref = "uuid-generator" }
jgrapht-core = { module = "org.jgrapht:jgrapht-core", version.ref = "jgrapht" }
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
lets-plot-kotlin-jvm = { module = "org.jetbrains.lets-plot:lets-plot-kotlin-jvm", version.ref = "lets-plot-kotlin" }
lets-plot-image-export = { module = "org.jetbrains.lets-plot:lets-plot-image-export", version.ref = "lets-plot-image" }

# Test libraries
mockk-jvm = { module = "io.mockk:mockk-jvm", version.ref = "mockk" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-konform-jvm = { module = "io.kotest:kotest-assertions-konform-jvm", version.ref = "kotest" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-native" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlinx-kover" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }

[bundles]
kotest = ["kotest-runner-junit5", "kotest-assertions-core", "kotest-assertions-konform-jvm"]
