[versions]
kotlin = "2.3.0"
kotlinx-kover = "0.9.5"
ktlint = "14.0.1"
graalvm-native = "0.11.4"
sonarqube = "7.2.2.6593"
jreleaser = "1.22.0"
release = "3.1.0"
picocli = "4.7.5"
konform = "0.11.1"
choco-solver = "4.10.18"
uuid-generator = "5.1.1"
jgrapht = "1.5.2"
commons-math3 = "3.6.1"
lets-plot-kotlin = "4.11.2"
lets-plot-image = "4.7.3"
mockk = "1.14.6"
kotest = "6.1.2"
kotlinx-serialization = "1.10.0"
kotlinx-datetime = "0.6.2"
sl4j = "2.0.17"

[libraries]
picocli = { module = "info.picocli:picocli", version.ref = "picocli" }
picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "picocli" }
konform-jvm = { module = "io.konform:konform-jvm", version.ref = "konform" }
choco-solver = { module = "org.choco-solver:choco-solver", version.ref = "choco-solver" }
uuid-generator = { module = "com.fasterxml.uuid:java-uuid-generator", version.ref = "uuid-generator" }
jgrapht-core = { module = "org.jgrapht:jgrapht-core", version.ref = "jgrapht" }
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commons-math3" }
lets-plot-kotlin-jvm = { module = "org.jetbrains.lets-plot:lets-plot-kotlin-jvm", version.ref = "lets-plot-kotlin" }
lets-plot-image-export = { module = "org.jetbrains.lets-plot:lets-plot-image-export", version.ref = "lets-plot-image" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
kotlinx-datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime-jvm", version.ref = "kotlinx-datetime" }
slf4j-nop = { module = "org.slf4j:slf4j-nop", version.ref = "sl4j" }

# Test libraries
mockk-jvm = { module = "io.mockk:mockk-jvm", version.ref = "mockk" }
kotest-runner-junit5 = { module = "io.kotest:kotest-runner-junit5", version.ref = "kotest" }
kotest-assertions-core = { module = "io.kotest:kotest-assertions-core", version.ref = "kotest" }
kotest-assertions-konform-jvm = { module = "io.kotest:kotest-assertions-konform-jvm", version.ref = "kotest" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
graalvm-native = { id = "org.graalvm.buildtools.native", version.ref = "graalvm-native" }
kotlinx-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlinx-kover" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
jreleaser = { id = "org.jreleaser", version.ref = "jreleaser" }
release = { id = "net.researchgate.release", version.ref = "release" }

[bundles]
kotest = ["kotest-runner-junit5", "kotest-assertions-core", "kotest-assertions-konform-jvm"]
