name: Bellum Tag Release Workflow CI
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'The tag to release'
        required: true

env:
  JAVA_VERSION: '25'
  JAVA_DISTRO: 'graalvm'

jobs:
  gradle_master_build:
    name: Gradle Release Task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.tag }} # This checks out the specific tag that triggered the workflow
          fetch-depth: 0

      - uses: n1hility/cancel-previous-runs@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup GraalVM
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: ${{ env.JAVA_DISTRO }}
          cache: 'gradle'

      - name: Running gradle task
        uses: gradle/actions/setup-gradle@v4

      - name: Running gradle task
        run: ./gradlew clean nativeCompile jreleaserRelease
        env:
          JRELEASER_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}